### ISSUE TITLE
Confused: Does it run WPE Webkit?

### ISSUE THREAD

**Issue by SamDecrock** [WebReflection/electroff#1]
I've been reading through your Medium articles and I'm confused.

For a second, I thought you created an Electron-like framework that used WPE Webkit to render the application GPU of the Raspberry Pi. Is it?

**Comment by WebReflection** [comment]
this module works with *every* browser on this planet, compatible with *Proxy*, hence it works with WPEWebKit too 👋

**Comment by WebReflection** [comment]
P.S. yes, I'm publishing on AUR (ArhLinux Users Repository) WPEWebKit HW accelerated binaries, and it works with this module too, as this module works with every browser, *including* WPE

**Comment by SamDecrock** [comment]
Ah, ok, but I still need to run WPEWebKit separately, I had the feeling it was built-in. Which would actually be pretty nice for makers.

**Comment by WebReflection** [comment]
an npm module cannot literally provide WPEWebKit ... so I'm not sure what you're asking.

yet, if you are on ArchLinux, you're good to go with both WPE and this module.
